language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer install -n

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi