language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
install:
  - composer install -n

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - php test/ModelUtilsTest.php

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
